name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: yarn build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build # will run `yarn build` command
    - name: yarn test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test # will run `yarn test` command
